apiVersion: v1
data:
  jws-kubeconfig-dibs81: eyJhbGciOiJIUzI1NiIsImtpZCI6ImRpYnM4MSJ9..zswinIi2cO3Y1qB_b-jT3S-8eUbD7XfGGY78ryGCXWQ
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1ERXdNekEzTlRNMU9Gb1hEVE15TURFd01UQTNOVE0xT0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTklGCnF1MjJmVDdKVVJpTFpLbUM3TUZwaUQxN2Y4T3hnSlB3R25vNDZNc1VuQVVRQmVXbTIya2JLQzlhRDNhVGJkeTAKT0hnZFk3YndYWS9NKzZ1dEtMcnlmRUlHa1JnckJOWHJGZnVLaVVDSlQ0ajNFQUZ3MHpBaTF1eWJUbjZJbmIzTQpUMTVnOGdOVU5UejYyZTZxc3U2QkFvdndFRWZmQjN5MFFXSVBFNDZ4OUMvUFVNTTh1SmxCN1RJY0g2Z29JSWRVCjJ2U1p1Z1BoVmx1SVBFT3VNRE0vdiswTE9MbjV4RTd0bC80dEdnejJqcDdaQ3BVOUNoa3FtZjk3Y0p6YVNVSEIKSzhmOHhkMHl1Qi9WazJ0Zm1odXBMbG5CbWRiTzU3YXN3aHFtcGhpb1NLeEY0cHNZbHB0NHBJbFFqZDZQR2RVTAppNEE0aUxjVDNnTW5LQ0xQdWFVQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZMakJJaXlMODA2SkE5WkMxRkptTW1HU1g1eHBNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRE1OZ0RVeVFGVzJISnpJU3FpMgpoWjQrOG9IbERyWm1yZWdpVEgyTm1pcDMxK3VhcktMdnk0NjU4WE80Z2JmYm1xQ25oVnMxUVQ2VVlXVHg2K2dXClRvcDNBSWZMK3BRQnpzdmlHSDd0YTNrZnVXUkx1T1BjcHFpR1NMZk15bHovK0xWNUR4VEJEeHYxQUFobDJjcUsKSm1vNHhMM1RCTXAvTkcvTGNudktBejBJK3llUVhLbm80MUtBMnhRYzI5MlUzRmlud1lVakNYU1RYTmxkY0dhSQpTZjEvbnBtZGJ2WUcwNVFlY2VmZ1pZRENlbWxPUmhiSTNwdVlsdzVJbWhGdHhIUUdNRjJLNkxFUHNQdjB6OEZSCmU1VHRrb2NHK3hzaXRaYmRyT0xuNU92NWJ5dGpmeXVtekxUVlpiWnJmZC95TTd2aUhlenRDM3NuUHM3WTN2bDkKLy9jPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        server: https://192.168.10.25:6443
      name: ""
    contexts: null
    current-context: ""
    kind: Config
    preferences: {}
    users: null
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-03T07:54:15Z"
  name: cluster-info
  namespace: kube-public
  resourceVersion: "424"
  uid: d26ed77a-41b4-4894-af5c-8319dbfcee3a
